services:
  ingress:
    volumes:
      - ./certs/ServerCerts:/etc/nginx/certs/ServerCerts:ro

  app:
    volumes:
      - ./Onix/patches/StatusPageService.ts:/usr/src/Common/Server/Services/StatusPageService.ts:ro

  probe-ingest:
    volumes:
      - ./Onix/patches/CustomCodeMonitorCriteria.ts:/usr/src/app/node_modules/Common/Server/Utils/Monitor/Criteria/CustomCodeMonitorCriteria.ts:ro

  probe-2:
    deploy:
      replicas: 0
